name: Backup JSON Server Database

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch JSON Server Database
        run: |
          mkdir -p data
          
          for endpoint in applications comments feedbacks foodTypes likes posts saveMethod twCities userReadComments userReadPosts users; do
            echo "Fetching $endpoint..."
            
            response=$(curl --write-out "%{http_code}" --silent --output "data/$endpoint.json" "https://json-server-vercel-5mr9.onrender.com/$endpoint")

            if [ "$response" -ne 200 ]; then
              echo "Error fetching $endpoint (HTTP Code: $response), restoring previous data."
              git checkout -- "data/$endpoint.json" || echo "File does not exist, skipping restore."
            fi
          done


      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git diff --staged --quiet || git commit -m "Automated Backup - $(date)"
          git pull --rebase origin main
          git push origin main